name: brazillian
version: 2.0.0
description: A library to generate, validate and format Brazilian data, such as CPF, CNPJ, Phones, Currency and many other things.
homepage: https://github.com/this-is-allan/brazillian
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
dev_dependencies:
  test: ^1.16.0-nullsafety.17
